### ISSUE TITLE
REST API docs

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/website#4]
As API consumer I want to see API documentation with code examples to learn how APIs work. 

## Definition of done
- [ ] User can and browse see 3-column API docs for all platform's exposed open APIs in developer portal
- [ ] Each API doc contains code examples for Shell, JS, java and and Python
- [ ] For each API, I can download the OAS spec API description

**Comment by kyyberi** [comment]
Internal description format for APIs is RAML. We need to test open source tool (https://github.com/wdullaer/raml2slate) which generates API docs skeleton from RAML.

**Comment by kyyberi** [comment]
I tested the raml2html module with cli. It seems to offer some beginning 

``raml2html --theme 'raml2html-slate-theme' api.raml > view.html``

![screenshot_2019-01-02 platform of trust translator documentation 1](https://user-images.githubusercontent.com/1927158/50588761-3cd03880-0e8c-11e9-8435-b5561d2c84c2.png)

![screenshot_2019-01-02 platform of trust translator documentation](https://user-images.githubusercontent.com/1927158/50588763-4063bf80-0e8c-11e9-8331-0d00aa143f39.png)

**Comment by kyyberi** [comment]
It lacks the code examples which is golden for developers. I'm wondering if we need to use slate itself and for that we need spec file as markdown file.

**Comment by kyyberi** [comment]
I tested some tools. 

RAML -> swagger 2.0
``api-spec-converter --from=raml --to=swagger_2 ./api.raml > swagger.json``
 -> Fatal YAMLError: Unsupported RAML version: '#%RAML 1.0' 
Does not support RAML 1.0 version

RAML -> OAS20
git clone git@github.com:mulesoft/oas-raml-converter.git
``./lib/bin/converter.js --from RAML --to OAS20 ../translator-skeleton-python/docs/api.raml > ../translator-skeleton-python/docs/swagger.json`` 
works with this sample

OAS -> Slate required md file
npm install -g swagger-to-slate
swagger-to-slate -i ../translator-skeleton-python/docs/swagger.json ../translator-skeleton-python/docs/
Works with the sample

**Comment by lietu** [comment]
Well we need
1) a plan on where to publish
2) a plan on what to publish
3) a plan on how to make the content to be published
4) automation for steps 1-3 as far as possible in the development backlog

**Comment by kyyberi** [comment]
> Well we need
> 
>     1. a plan on where to publish
> 
>     2. a plan on what to publish
> 
>     3. a plan on how to make the content to be published
> 
>     4. automation for steps 1-3 as far as possible in the development backlog

About the process. I took a look at the html rendering results and doing manual finetuning with those most likely is painful and time consuming. The modifications need to be done before converting RAML to human readable documentation format. 

As the end result developer reads the API documentations from Developer Portal (where we publish). That is what we publish in the end. Here's some steps how that might be created: 

**MVP**

- RAML spec can be published to where ever (technically) in public space from where it can be edited and downloaded (for further steps). Why not Github? RAML spec files here refers to platform public APIs docs (what we publish). 
- Open API spec files are generated from RAML and would be published in the same place with RAML spec files. 
- Those OAS files are linked to Developer Portal for download.  
- API Owner / manager (role) modifies textual content of the RAML spec files to include necessary business related information and includes missing tips for the API consumers. That is what I have done with Open API spec files before publishing. 
- Developer Portal reads the RAML files from github and renders the documentation in Portal for all the RAML files. The result lacks code language specific code examples but contain curl examples. 

**Full API docs**
- RAML spec can be published to where ever (technically) in public space from where it can be edited and downloaded (for further steps). Why not Github? RAML spec files here refers to platform public APIs docs (what we publish). 
- Open API spec files are generated from RAML and would be published in the same place with RAML spec files. 
- Those OAS files are linked to Developer Portal for download.  
- Automatically convert OAS files to Slate markup page. 
- API Owner / manager (role) modifies textual content of the Slate markup doc. 
- Slate markup document is published in subdomain or /docs url where all the final result API docs are. This requires that we run Slate separately from portal (unless @MikaHamalainen finds a way to integrate Slate to React UI.  This option enables code language specific examples. 

We need to decide which way to go. Rigidly keep all in one portal or because of convenience accept that detailed API docs are running on top of separate service.

**Comment by kyyberi** [comment]
We have now the RAML sources to work with. https://github.com/PlatformOfTrust/developer.oftrust.net/tree/master/docs/RAML-sources 

I'll test the process to generate wanted API documentation from those. I'll need to discuss with @MikaHamalainen how the generated content is easiest to include in React front. Also I need to check in which step manual modifications makes sense. Of course documenting the process as well.

**Comment by kyyberi** [comment]
Decision was made to keep up docs as separate eg not integrated to portal at the moment. Slick and easy way to include 3-column API docs model was not found. API consumer is not directed to detailed documentation anyway, but instead we offer for first encounter getting started packages. API Docs are for finding details after getting started. We will use Slate for showing the documentation for API consumers.  

To finalize the internal process to create API docs with Slate I've set up docs.oftrust.net repository. I'll test and document the process first. Then we can evaluate it and take into use.

**Comment by kyyberi** [comment]
Framework in place, content creation and update needed.
