### ISSUE TITLE
Domain to access Developer Portal

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/website#9]
As a developer I want to access PoT Develeloper Portal from developer.oftrust.net because that is the industry default and expected subdomain.

**Comment by kyyberi** [comment]
IP address is needed. We'll use Azure.

**Comment by lietu** [comment]
There should be a 301 redirect set up from `developers` -> `developer`

**Comment by kyyberi** [comment]
> There should be a 301 redirect set up from `developers` -> `developer`

Yes, or then we just use developers.oftrust.net

**Comment by lietu** [comment]
Well either way the other one should have a 301 to the other, as both are commonly used and devs typically just try to guess which one it is when typing the address to their address bar :)
